### PR TITLE
Adding jdk.jfr module for flight recording

### LINKED ISSUE #10: Check if we can do flight recording with jdk4py

### PR DESCRIPTION
**Pull request by bloussou**
Fix #10 

Fix found here : https://stackoverflow.com/a/52334392

### CODE REVIEW

**Comment by fabiencelier** [comment]
Can you add a small test to ensure it works?

**Comment by fabiencelier** [comment]
Can you also compare the size of the packages with and without the new modules ?

**Comment by bloussou** [comment]
> Can you also compare the size of the packages with and without the new modules ?

Packages growth is 0.4MB (for conda and pip)

**Comment by bloussou** [comment]
> Can you add a small test to ensure it works?

The issue is only happening with azul zulu, therefore I don't think there is a simple way to test it works

**Review by fabiencelier — APPROVED** [review]

**Pull request merged**
