### PR TITLE
Upload wheel to GitHub

### PR DESCRIPTION
**Pull request by fabiencelier**
This gives access to the artifacts without releasing a new version

### CODE REVIEW

**Comment by fabiencelier** [comment]
Working in tests: https://github.com/atoti/jdk4py/actions/runs/233042288

**Comment by tibdex** [comment]
Should we only upload the wheels built with the latest version of Python?

**Comment by fabiencelier** [comment]
> Should we only upload the wheels built with the latest version of Python?

Build only happen with Python 3.8

**Review by tibdex — APPROVED** [review]
:octocat:

**Comment by fabiencelier** [comment]
It works: https://github.com/atoti/jdk4py/actions/runs/233064235
It would be nice to only trigger the upload to Pypi only if the version has changed (or some logic like that)

**Pull request merged**
